services:
  - docker

env:
  - NODE_VERSION=8-jessie
  - NODE_VERSION=10-jessie

script:
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - docker build -t node:$NODE_VERSION --build-arg NODE_IMAGE="node:${NODE_VERSION}" .
  - docker image list
  - docker tag node:$NODE_VERSION $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)
  - docker push $DOCKER_USERNAME/probot-hello:$NODE_VERSION-$(git rev-parse HEAD)

after_success: |
  set -x -v -e;
  if [ $NPM_TARGET == "test" ]; then
    docker tag probot-hello probot-hello:$(git rev-parse HEAD);
  else
    echo "skipping docker tag";
  fi;
  docker image list;
  set +x +v;
