sudo: required
services:
  - docker

before_install:
  - docker pull node:8-onbuild

env:
  - NPM_TARGET=test
  - NPM_TARGET=lint
  - NPM_TARGET=coverage

install:
  - docker build -t probot-hello .

script:
  - docker run --rm probot-hello npm run $NPM_TARGET

after_success: |
  set -x -v -e;
  if [ $NPM_TARGET == "test" ]; then
    docker tag probot-hello probot-hello:$(git rev-parse HEAD);
  else
    echo "skipping docker tag";
  fi;
  docker image list;
  set +x +v;
